In [1]:
pip install deepchem

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 693.2/693.2 kB 10.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.2/42.2 MB 20.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 29.7/29.7 MB 26.0 MB/s eta 0:00:00
  Attempting uninstall: scipy
    Found existing installation: scipy 1.10.1
    Uninstalling scipy-1.10.1:
      Successfully uninstalled scipy-1.10.1


In [2]:
import deepchem as dc

In [3]:
import numpy as np

In [4]:
x=np.random.random((4,5))
y=np.random.random((4,1))

In [5]:
x

array([[0.46383045, 0.43321227, 0.0450624 , 0.42446206, 0.42648137],
       [0.31766884, 0.76981543, 0.78817547, 0.36791064, 0.1564186 ],
       [0.05005171, 0.02459051, 0.86916343, 0.61403257, 0.96329703],
       [0.16500708, 0.34513716, 0.72349507, 0.67770176, 0.09249356]])

In [6]:
y

array([[0.02136602],
       [0.36784424],
       [0.58244275],
       [0.6666355 ]])

In [7]:
dataset = dc.data.NumpyDataset(x, y)

In [8]:
print(dataset.X)

[[0.46383045 0.43321227 0.0450624  0.42446206 0.42648137]
 [0.31766884 0.76981543 0.78817547 0.36791064 0.1564186 ]
 [0.05005171 0.02459051 0.86916343 0.61403257 0.96329703]
 [0.16500708 0.34513716 0.72349507 0.67770176 0.09249356]]


In [9]:
print(dataset.y)

[[0.02136602]
 [0.36784424]
 [0.58244275]
 [0.6666355 ]]


In [10]:
np.array_equal(x,dataset.X)
np.array_equal(y,dataset.y)

True

In [11]:
#dc.molnet(molecularNet contains preprocessed datasetsetd)
#dc.molnet.load_tox21(load and process)
tox21_tasks,tox21_datasets,transformer=dc.molnet.load_tox21()

[16:52:54] WARNING: not removing hydrogen atom without neighbors
[16:53:05] WARNING: not removing hydrogen atom without neighbors


In [12]:
tox21_tasks

['NR-AR',
 'NR-AR-LBD',
 'NR-AhR',
 'NR-Aromatase',
 'NR-ER',
 'NR-ER-LBD',
 'NR-PPAR-gamma',
 'SR-ARE',
 'SR-ATAD5',
 'SR-HSE',
 'SR-MMP',
 'SR-p53']

In [13]:
len(tox21_tasks)

12

In [14]:
tox21_datasets

(<DiskDataset X.shape: (6264, 1024), y.shape: (6264, 12), w.shape: (6264, 12), task_names: ['NR-AR' 'NR-AR-LBD' 'NR-AhR' ... 'SR-HSE' 'SR-MMP' 'SR-p53']>,
 <DiskDataset X.shape: (783, 1024), y.shape: (783, 12), w.shape: (783, 12), ids: ['N#C[C@@H]1CC(F)(F)CN1C(=O)CNC1CC2CCC(C1)N2c1ncccn1'
  'CN(C)C(=O)NC1(c2ccccc2)CCN(CCC[C@@]2(c3ccc(Cl)c(Cl)c3)CCCN(C(=O)c3ccccc3)C2)CC1'
  'CSc1nnc(C(C)(C)C)c(=O)n1N' ...
  'O=C(O[C@H]1CN2CCC1CC2)N1CCc2ccccc2[C@@H]1c1ccccc1'
  'C#C[C@]1(O)CC[C@H]2[C@@H]3CCC4=CC(=O)CC[C@@H]4[C@H]3C(=C)C[C@@]21CC'
  'NC(=O)C(c1ccccc1)(c1ccccc1)[C@@H]1CCN(CCc2ccc3c(c2)CCO3)C1'], task_names: ['NR-AR' 'NR-AR-LBD' 'NR-AhR' ... 'SR-HSE' 'SR-MMP' 'SR-p53']>,
 <DiskDataset X.shape: (784, 1024), y.shape: (784, 12), w.shape: (784, 12), ids: ['CC1(C)S[C@@H]2[C@H](NC(=O)Cc3ccccc3)C(=O)N2[C@H]1C(=O)O.CC1(C)S[C@@H]2[C@H](NC(=O)Cc3ccccc3)C(=O)N2[C@H]1C(=O)O.c1ccc(CNCCNCc2ccccc2)cc1'
  'CC(C)(c1ccc(Oc2ccc3c(c2)C(=O)OC3=O)cc1)c1ccc(Oc2ccc3c(c2)C(=O)OC3=O)cc1'
  'Cc1cc(C(C)(C)C)c(O)c(C)c1

In [15]:
train_dataset,valid_dataset,test_dataset=tox21_datasets

In [16]:
train_dataset.X.shape

(6264, 1024)

In [17]:
valid_dataset.X.shape

(783, 1024)

In [18]:
test_dataset.X.shape

(784, 1024)

In [19]:
np.shape(train_dataset.y)

(6264, 12)

In [20]:
np.shape(valid_dataset.y)

(783, 12)

In [21]:
np.shape(test_dataset.y)

(784, 12)

In [22]:
#multitaskclassifier
model=dc.models.MultitaskClassifier(n_tasks=12,n_features=1024,layer_sizes=[1000])

In [23]:
#train the dataset
model.fit(train_dataset,nb_epoch=10)

0.5116795857747396

In [24]:
metric = dc.metrics.Metric(dc.metrics.roc_auc_score, np.mean)

In [26]:
train_scores = model.evaluate(train_dataset, [metric], transformer)
test_scores = model.evaluate(test_dataset, [metric], transformer)


In [27]:
print(train_scores)
print(test_scores)

{'mean-roc_auc_score': 0.9587564237571177}
{'mean-roc_auc_score': 0.6858837975222478}
